Work in progress - do not merge
101digital/payments-component pull request #16
Opened 2023-02-16 07:26 UTC by hiteshdigit101

2023-02-16 10:58 UTC, sharmal33 requested changes

2023-02-16 10:58 UTC, sharmal33 commented on src/components/adb-nad-account-link/index.tsx
>          "Your DuitNow ID has been successfully reactivated"
move this to translations file

2023-02-16 10:58 UTC, sharmal33 commented on src/components/transfer-details-component/index.tsx
>                          color: "#1b1b1b",
use color palette

2023-02-17 02:22 UTC, hiteshdigit101 commented on src/components/adb-nad-account-link/index.tsx
>          "Your DuitNow ID has been successfully reactivated"
moved to translation file

2023-02-17 02:22 UTC, hiteshdigit101 commented on src/components/transfer-details-component/index.tsx
>                          color: "#1b1b1b",
changed from static color to theme component colors

2023-02-17 02:45 UTC, sharmal33 approved these changes

2023-02-17 02:46 UTC, merged