Adb 813
101digital/payments-component pull request #6
Opened 2023-02-01 08:35 UTC by hiteshdigit101

ADB-813
ADB-809
ADB-846
ADB-843
ADB-906

2023-02-01 10:14 UTC, sharmal33 requested changes
- don't use inline styles 
- plz use theme component colors

2023-02-01 10:14 UTC, sharmal33 commented on src/components/adb-nad-account-register/index.tsx
> +            labelColor={"#1B1B1B"}
plz use themes colors

2023-02-01 10:14 UTC, sharmal33 commented on src/components/adb-nad-account-register/index.tsx
> +    backgroundColor: "#F5F5F5",
plz use themes colors

2023-02-01 10:14 UTC, sharmal33 commented on src/components/adb-nad-account-register/index.tsx
> +    backgroundColor: "#D9D9D9",
plz use themes colors

2023-02-01 10:14 UTC, sharmal33 commented on src/components/adb-nad-account-register/index.tsx
> +    color: "#1B1B1B",
plz use themes colors

2023-02-01 10:14 UTC, sharmal33 commented on src/components/adb-nad-account-register/index.tsx
> -    color: '#1B1B1B',
plz use themes colors

2023-02-01 10:14 UTC, sharmal33 commented on src/components/proxy-transfer-component/error-modal.tsx
> +        }}
don't write inline styles

2023-02-01 10:14 UTC, sharmal33 commented on src/components/proxy-transfer-component/error-modal.tsx
> +        }}
don't write inline styles

2023-02-02 05:36 UTC, hiteshdigit101 commented on src/components/adb-nad-account-register/index.tsx
> +            labelColor={"#1B1B1B"}
Updated to theme component

2023-02-02 05:36 UTC, hiteshdigit101 commented on src/components/adb-nad-account-register/index.tsx
> +    backgroundColor: "#F5F5F5",
Updated to theme colors

2023-02-02 05:36 UTC, hiteshdigit101 commented on src/components/adb-nad-account-register/index.tsx
> +    backgroundColor: "#D9D9D9",
Updated to theme component

2023-02-02 05:38 UTC, hiteshdigit101 commented on src/components/adb-nad-account-register/index.tsx
> +    color: "#1B1B1B",
Updated to theme colors

2023-02-02 05:38 UTC, hiteshdigit101 commented on src/components/adb-nad-account-register/index.tsx
> -    color: '#1B1B1B',
Updated to theme colors

2023-02-02 05:38 UTC, hiteshdigit101 commented on src/components/proxy-transfer-component/error-modal.tsx
> +        }}
Moved to style sheet

2023-02-02 05:38 UTC, hiteshdigit101 commented on src/components/proxy-transfer-component/error-modal.tsx
> +        }}
Moved to style sheet

2023-02-02 17:59 UTC, sharmal33 approved these changes

2023-02-03 02:47 UTC, merged