ADBP-UI-Bugs
101digital/payments-component pull request #70
Opened 2023-03-24 07:07 UTC by KashifM101

Fixes remaining
Qroutbound fixes
Alignment fixes

2023-03-27 03:58 UTC, sharmal33 requested changes

2023-03-27 03:58 UTC, sharmal33 commented on src/components/selector-component/index.tsx
> +          <View style={{flexDirection: "row", alignItems:"center"  }}>
don't do inline style

2023-03-27 03:58 UTC, sharmal33 commented on src/components/transfer-confirmation-component/style.ts
>        color: '#3F3F3F',
plz use theme colors

2023-03-27 03:59 UTC, KashifM101 commented on src/components/transfer-confirmation-component/style.ts
>        color: '#3F3F3F',
Ok

2023-03-28 04:43 UTC, sharmal33 approved these changes

2023-03-28 04:55 UTC, merged