ADBP-1929 (Thousand separator)
101digital/payments-component pull request #74
Opened 2023-03-29 09:13 UTC by KashifM101

Link to Jira:
https://101digital.atlassian.net/browse/ADBP-1929

Thousand separators inside the textinput field fixed with range slider.

2023-03-30 00:51 UTC, sharmal33 requested changes

2023-03-30 00:51 UTC, sharmal33 commented on src/components/qr-transfer-component/qr-registration-component/setup-qr-account-component/index.tsx
>  import DangerIcon from "../../../../assets/icons/danger-icon";
import all icons from here 
eg : import {ArrowRightBoldIcon, DangerIcon} from "../../../../assets/icons";

2023-03-30 02:52 UTC, KashifM101 commented on src/components/qr-transfer-component/qr-registration-component/setup-qr-account-component/index.tsx
>  import DangerIcon from "../../../../assets/icons/danger-icon";
There are  some issue in dangericon.ts Thats why it's directly used from there not from import

2023-03-31 00:24 UTC, sharmal33 requested changes

2023-03-31 00:24 UTC, sharmal33 commented on src/components/qr-transfer-component/qr-registration-component/setup-qr-account-component/index.tsx
>  import DangerIcon from "../../../../assets/icons/danger-icon";
what is the issue?

2023-03-31 07:49 UTC, sharmal33 approved these changes

2023-03-31 09:15 UTC, merged