ADBP-2353
101digital/payments-component pull request #75
Opened 2023-03-30 08:08 UTC by KashifM101

Link to Jira:
https://101digital.atlassian.net/browse/ADBP-2353

2023-03-31 00:28 UTC, sharmal33 requested changes

2023-03-31 00:28 UTC, sharmal33 commented on src/components/qr-transfer-component/qr-inbound-transfer/index.tsx
>              ]}
why inline styles ?

2023-03-31 00:28 UTC, sharmal33 commented on src/components/qr-transfer-component/qr-registration-component/setup-qr-account-component/index.tsx
>  import RnRangeSlider from "../../components/range-slider";
plz import all icons from icon.index file

2023-03-31 02:52 UTC, KashifM101 commented on src/components/qr-transfer-component/qr-inbound-transfer/index.tsx
>              ]}
i'll restructure it.

2023-03-31 02:52 UTC, KashifM101 commented on src/components/qr-transfer-component/qr-registration-component/setup-qr-account-component/index.tsx
>  import RnRangeSlider from "../../components/range-slider";
ok

2023-04-05 00:25 UTC, sharmal33 approved these changes

2023-04-05 00:25 UTC, merged