ADBP-1547
101digital/payments-component pull request #76
Opened 2023-04-02 11:17 UTC by KashifM101

Link to Jira:
https://101digital.atlassian.net/browse/ADBP-1547
error issue fixed

2023-04-04 03:25 UTC, khoi101digital approved these changes

2023-04-04 03:26 UTC, khoi101digital requested changes

2023-04-04 03:26 UTC, khoi101digital commented on src/components/proxy-transfer-component/index.tsx
> +import {DangerIcon} from "../../assets/icons/danger-icon";
please import icon from index file

2023-04-05 02:58 UTC, sharmal33 approved these changes

2023-04-05 02:58 UTC, merged