colors for both debit and credit are defined for transaction history
101digital/payments-component pull request #84
Opened 2023-04-05 05:33 UTC by usamabutt101

### Why

Please give a short description why these code changes are being made, by replacing this line.

Link to Jira ticket: <place here>

### ToDo

- [ ]
- [ ]
- [ ]

If this is a `Draft:` or `WIP:` PR, please describe still needed actions, else delete section

2023-04-06 07:35 UTC, sharmal33 requested changes

2023-04-06 07:35 UTC, sharmal33 commented on src/components/adb-transaction-history/index.tsx
>      value: 90,
plz move all title values in to translation file

2023-04-06 07:35 UTC, sharmal33 commented on src/components/adb-transaction-history/index.tsx
> +    if (wallets.length > 0 && wallets[0].bankAccount?.accountSubType === 'SavingAccount-i') {
this logic is wrong
**wallets[0]** some time it return different account type.

2023-04-06 07:35 UTC, sharmal33 commented on src/components/adb-transaction-history/index.tsx
> +    flexDirection: 'row',
plz move all colors into translation file

2023-04-07 04:21 UTC, usamabutt101 commented on src/components/adb-transaction-history/index.tsx
> +    if (wallets.length > 0 && wallets[0].bankAccount?.accountSubType === 'SavingAccount-i') {
I have asked this from Viet at that time.

2023-04-07 04:29 UTC, usamabutt101 commented on src/components/adb-transaction-history/index.tsx
> +    flexDirection: 'row',
resolved!

2023-04-10 02:25 UTC, sharmal33 approved these changes

2023-04-10 02:43 UTC, merged