ADBP-2252:Bug fixed
101digital/payments-component pull request #89
Opened 2023-04-10 00:34 UTC by KashifM101

Link to Jira:
https://101digital.atlassian.net/browse/ADBP-2252

2023-04-10 05:34 UTC, sharmal33 requested changes

2023-04-10 05:34 UTC, sharmal33 commented on src/components/transfer-details-component/index.tsx
> +    accountNumber: '104090713',
why accountNumber are hardcoded ?

2023-04-10 05:34 UTC, sharmal33 commented on src/components/transfer-details-component/index.tsx
> +    accountNumber: '104090713',
accoutType and accountNumber should return from API

2023-04-10 07:55 UTC, KashifM101 commented on src/components/transfer-details-component/index.tsx
> +    accountNumber: '104090713',
i don’t know anything about that @sharmal33 may be the one who had worked on it have the idea

2023-04-10 09:30 UTC, khoi101digital approved these changes

2023-04-11 00:53 UTC, sharmal33 commented on src/components/transfer-details-component/index.tsx
> +    accountNumber: '104090713',
can you ask this with @hiteshdigit101  
this values should return from api

2023-04-11 01:22 UTC, KashifM101 commented on src/components/transfer-details-component/index.tsx
> +    accountNumber: '104090713',
ok

2023-04-11 01:43 UTC, merged