feat(ADBP-2588) - Removed navigation on changing payment method [tran…
101digital/payments-component pull request #94
Opened 2023-04-11 03:30 UTC by hiteshdigit101

ADBP-2588 Implemented

2023-04-11 07:41 UTC, sharmal33 requested changes

2023-04-11 07:41 UTC, sharmal33 commented on src/components/transfer-out-component/index.tsx
> +            console.log("Number --> ", number);
remove log

2023-04-11 07:41 UTC, sharmal33 commented on src/components/transfer-out-component/style.ts
> +      color: "#FCFCFC",
use theme colors

2023-04-11 07:41 UTC, sharmal33 commented on src/components/transfer-out-component/style.ts
>      title: {
use theme colors

2023-04-11 07:41 UTC, sharmal33 commented on src/components/transfer-out-component/style.ts
> +      color: "#000000",
use theme colors

2023-04-12 03:42 UTC, hiteshdigit101 commented on src/components/transfer-out-component/style.ts
> +      color: "#FCFCFC",
removed log

2023-04-12 03:42 UTC, hiteshdigit101 commented on src/components/transfer-out-component/style.ts
> +      color: "#000000",
changed to theme colors

2023-04-12 03:42 UTC, hiteshdigit101 commented on src/components/transfer-out-component/style.ts
>      title: {
changed to theme colors

2023-04-13 03:54 UTC, catluong101digital commented on src/components/proxy-transfer-component/index.tsx
> +            >{`Please enter a valid ${proxyName.toLowerCase()}.`}</Text>
can you use it from translation instead

2023-04-13 03:54 UTC, catluong101digital commented on src/components/proxy-transfer-component/index.tsx
>      fontFamily: "Poppins",
use font from theme component

2023-04-13 03:54 UTC, catluong101digital commented on src/components/select-transfer-type-component/index.tsx
> +        {paymentType?.Name !== "AccountNumber" && (
can we move this string "AccountNumber" to a constant file

2023-04-13 03:54 UTC, catluong101digital commented on src/components/transfer-out-component/index.tsx
> +                <Text style={styles.labelTextStyle}>{"Account number"}</Text>
use text from translation

2023-04-13 03:54 UTC, catluong101digital commented on src/components/transfer-out-component/style.ts
>        color: '#FCFCFC',
use color from theme component

2023-04-13 03:54 UTC, catluong101digital commented on src/components/select-transfer-type-component/index.tsx
> +    () => paymentMethods.find((item) => item?.Name === "MobileNumber") || null,
can we move this to a constant file

2023-04-13 05:21 UTC, catluong101digital approved these changes

2023-04-15 23:25 UTC, sharmal33 approved these changes

2023-04-21 16:41 UTC, sharmal33 approved these changes

2023-04-23 11:25 UTC, merged